version: '3.4'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - '8088:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: api
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    ports:
      - '33068:3306'
    volumes:
      - db-data:/var/lib/mysql
  symfony:
    image: webdevops/php-apache-dev:8.0-alpine
    ports:
      - '8108:80'
    working_dir: /app
    env_file:
      - ./symfony/.env
    volumes:
      - ./symfony:/app/
    links:
      - mysql
  # api:
  #   image: webdevops/php-apache-dev:8.0-alpine
  #   ports:
  #     - '8108:80'
  #   working_dir: /app
  #   env_file:
  #     - ./api/.env
  #   volumes:
  #     - ./api:/app/
  #   links:
  #     - mysql
  app:
    image: node:16.15.1
    working_dir: /var/www/html
    #entrypoint: /bin/bash
    #expose:
    #  - 8008
    ports:
      - 8008:8008
    volumes:
      - ./:/var/www/html/
    command: 'npm run dev' #tty: true
    links:
      - mysql
      - symfony
volumes:
  db-data:
